apiVersion: v1
kind: Pod
metadata:
  name: tempest-worker
spec:
  volumes:
    - name: tempest-workdir
      emptyDir: {}
    - name: cloud-passwd
      secret:
         secretName: openstack-config-secret
    - name: clouds-config
      configMap:
          name: openstack-config
    - name: pre-install
      emptyDir: {}
    - name: whitebox-plugin
      hostPath:
        path: /home/stack/whitebox-tempest-plugin
    - name: tempest-script
      hostPath:
        path: /home/stack/tempest
    - name: tempest-logs
      hostPath:
        path: /home/stack/tempest/external_files

  containers:
    - name: tempest-container
      image: quay.io/podified-antelope-centos9/openstack-tempest:current-podified
      command: ["/usr/bin/dumb-init", "sleep", "infinity"]
      volumeMounts:
        - mountPath: "/home"
          name: tempest-workdir
        - mountPath: "/etc/openstack"
          name: pre-install
        - mountPath: "/etc/openstack/clouds.yaml"
          name: clouds-config
          subPath: clouds.yaml
        - mountPath: "/etc/openstack/secure.yaml"
          name: cloud-passwd
          subPath: secure.yaml
        - mountPath: "/home/stack/whitebox-tempest-plugin"
          name: whitebox-plugin
        - mountPath: "/home/stack/tempest"
          name: tempest-script
        - mountPath: "/var/lib/tempest/external_files"
          name: tempest-logs
      env:
        - name: OS_CLOUD
          valueFrom:
            configMapKeyRef:
              name: openstack-config
              key: OS_CLOUD
